// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TaskSharper.Launcher.WPF.Test.UI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LoginGoogle_Success
        /// </summary>
        public void LoginGoogle_Success()
        {
            #region Variable Declarations
            WpfButton uILoginButton = this.UIMainWindowWindow.UILoginButton;
            WinWindow uILogindGoogleKontiGooWindow1 = this.UILogindGoogleKontiGooWindow.UILogindGoogleKontiGooWindow1;
            #endregion

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(210, 103));

            // Click 'Log ind – Google Konti – Google Chrome' window
            Mouse.Click(uILogindGoogleKontiGooWindow1, new Point(857, 710));

            // Click 'Log ind – Google Konti – Google Chrome' window
            Mouse.Click(uILogindGoogleKontiGooWindow1, new Point(1110, 728));

            // Click 'Log ind – Google Konti – Google Chrome' window
            Mouse.Click(uILogindGoogleKontiGooWindow1, new Point(1102, 688));

            // Click 'Log ind – Google Konti – Google Chrome' window
            Mouse.Click(uILogindGoogleKontiGooWindow1, new Point(1110, 798));

            // Click 'Log ind – Google Konti – Google Chrome' window
            Mouse.Click(uILogindGoogleKontiGooWindow1, new Point(945, 1189));
        }
        
        #region Properties
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UILogindGoogleKontiGooWindow UILogindGoogleKontiGooWindow
        {
            get
            {
                if ((this.mUILogindGoogleKontiGooWindow == null))
                {
                    this.mUILogindGoogleKontiGooWindow = new UILogindGoogleKontiGooWindow();
                }
                return this.mUILogindGoogleKontiGooWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UILogindGoogleKontiGooWindow mUILogindGoogleKontiGooWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "LoginLogoutBtn";
                    this.mUILoginButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILogindGoogleKontiGooWindow : WinWindow
    {
        
        public UILogindGoogleKontiGooWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Log ind – Google Konti – Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Log ind – Google Konti – Google Chrome");
            this.WindowTitles.Add("OAuth 2.0 Authentication Token Received – Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UILogindGoogleKontiGooWindow1
        {
            get
            {
                if ((this.mUILogindGoogleKontiGooWindow1 == null))
                {
                    this.mUILogindGoogleKontiGooWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUILogindGoogleKontiGooWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Log ind – Google Konti";
                    this.mUILogindGoogleKontiGooWindow1.WindowTitles.Add("Log ind – Google Konti – Google Chrome");
                    this.mUILogindGoogleKontiGooWindow1.WindowTitles.Add("OAuth 2.0 Authentication Token Received – Google Chrome");
                    #endregion
                }
                return this.mUILogindGoogleKontiGooWindow1;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUILogindGoogleKontiGooWindow1;
        #endregion
    }
}
