//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSharper.Calender.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskSharper.Calender.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskSharperCalendar.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string CalendarDay_Friday {
            get {
                return ResourceManager.GetString("CalendarDay_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string CalendarDay_Monday {
            get {
                return ResourceManager.GetString("CalendarDay_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string CalendarDay_Saturday {
            get {
                return ResourceManager.GetString("CalendarDay_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string CalendarDay_Sunday {
            get {
                return ResourceManager.GetString("CalendarDay_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string CalendarDay_Thursday {
            get {
                return ResourceManager.GetString("CalendarDay_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string CalendarDay_Tuesday {
            get {
                return ResourceManager.GetString("CalendarDay_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string CalendarDay_Wednesday {
            get {
                return ResourceManager.GetString("CalendarDay_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string CalendarMonth_April {
            get {
                return ResourceManager.GetString("CalendarMonth_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string CalendarMonth_August {
            get {
                return ResourceManager.GetString("CalendarMonth_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string CalendarMonth_December {
            get {
                return ResourceManager.GetString("CalendarMonth_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string CalendarMonth_February {
            get {
                return ResourceManager.GetString("CalendarMonth_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string CalendarMonth_January {
            get {
                return ResourceManager.GetString("CalendarMonth_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string CalendarMonth_July {
            get {
                return ResourceManager.GetString("CalendarMonth_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string CalendarMonth_June {
            get {
                return ResourceManager.GetString("CalendarMonth_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string CalendarMonth_March {
            get {
                return ResourceManager.GetString("CalendarMonth_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string CalendarMonth_November {
            get {
                return ResourceManager.GetString("CalendarMonth_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string CalendarMonth_October {
            get {
                return ResourceManager.GetString("CalendarMonth_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string CalendarMonth_September {
            get {
                return ResourceManager.GetString("CalendarMonth_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month .
        /// </summary>
        public static string MainWindow_Month_Button_Text {
            get {
                return ResourceManager.GetString("MainWindow_Month_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string MainWindow_Today_Button_Text {
            get {
                return ResourceManager.GetString("MainWindow_Today_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string MainWindow_Week_Button_Text {
            get {
                return ResourceManager.GetString("MainWindow_Week_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        public static string MonthView_Next_Button_Text {
            get {
                return ResourceManager.GetString("MonthView_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Month.
        /// </summary>
        public static string MonthView_Prev_Button_Text {
            get {
                return ResourceManager.GetString("MonthView_Prev_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        public static string WeekView_Next_Button_Text {
            get {
                return ResourceManager.GetString("WeekView_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Week.
        /// </summary>
        public static string WeekView_Prev_Button_Text {
            get {
                return ResourceManager.GetString("WeekView_Prev_Button_Text", resourceCulture);
            }
        }
    }
}
